# Generated by Django 3.0.7 on 2020-07-10 14:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResizeImagesRequests',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('image_size', django.contrib.postgres.fields.jsonb.JSONField()),
                ('save_format', models.CharField(max_length=3)),
                ('image_status', models.CharField(max_length=20)),
            ],
        ),
    ]
