# Generated by Django 3.0.8 on 2020-07-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20200710_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resizeimages',
            name='image',
            field=models.ImageField(upload_to='results'),
        ),
    ]
