# Generated by Django 3.0.8 on 2020-07-15 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20200714_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resizeimages',
            name='image_status',
        ),
    ]
